language: c
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew list gcc || brew install gcc && CC=gcc-9; fi
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: travis_wait 60 OPAMWITHDOC=false bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=goblint-cil
  matrix:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09
    - OCAML_VERSION=4.10
os:
  - linux
  - osx
osx_image: xcode11.2
